"""Deterministic, local-only demo data for development and screenshots.

The seed is intentionally independent of paid market/LLM providers.  It only
touches the dedicated demo account and rows marked with ``source='demo_seed'``.
"""
from datetime import date, datetime, timedelta
import math

from sqlalchemy.orm import Session

from app.core.security import get_password_hash
from app.models.analysis import Analysis
from app.models.company_financial import CompanyFinancial
from app.models.company_fundamental import CompanyFundamental
from app.models.document import Document
from app.models.expert_signal import ExpertSignal
from app.models.market import MarketData
from app.models.position import Position
from app.models.portfolio_trade import PortfolioTrade
from app.models.profile import UserProfile
from app.models.ranking_item import RankingItem
from app.models.ranking_snapshot import RankingSnapshot
from app.models.stock import Stock
from app.models.stock_kline import StockKline
from app.models.stock_quote import StockQuote
from app.models.trade_plan import TradePlan
from app.models.trade_signal import TradeSignal
from app.models.user import User
from app.models.user_stock_holding import UserStockHolding


DEMO_SOURCE = "demo_seed"
STOCKS = [
    ("000001", "平安银行", "银行", 10.35),
    ("000333", "美的集团", "家用电器", 68.20),
    ("000651", "格力电器", "家用电器", 39.85),
    ("002415", "海康威视", "计算机设备", 31.60),
    ("002594", "比亚迪", "汽车整车", 238.40),
]


def _clear_demo_rows(db: Session, user: User | None) -> None:
    """Remove only rows generated by this seed, preserving real user data."""
    if user:
        for model in (TradeSignal, TradePlan, PortfolioTrade, Position, Analysis, UserStockHolding):
            db.query(model).filter(model.user_id == user.id).delete(synchronize_session=False)
        db.query(UserProfile).filter(UserProfile.user_id == user.id).delete(synchronize_session=False)
    snapshot_ids = [x.id for x in db.query(RankingSnapshot).filter(RankingSnapshot.snapshot_type == DEMO_SOURCE).all()]
    if snapshot_ids:
        db.query(RankingItem).filter(RankingItem.snapshot_id.in_(snapshot_ids)).delete(synchronize_session=False)
        db.query(RankingSnapshot).filter(RankingSnapshot.id.in_(snapshot_ids)).delete(synchronize_session=False)
    db.query(ExpertSignal).filter(ExpertSignal.analysis_id.in_(db.query(Analysis.id).filter(Analysis.user_id == (user.id if user else -1)))).delete(synchronize_session=False)
    db.query(Document).filter(Document.source == DEMO_SOURCE).delete(synchronize_session=False)
    stock_ids = [x.id for x in db.query(Stock).filter(Stock.symbol.in_([s[0] for s in STOCKS])).all()]
    if stock_ids:
        for model in (MarketData, StockKline, StockQuote, CompanyFundamental, CompanyFinancial):
            db.query(model).filter(model.stock_id.in_(stock_ids)).delete(synchronize_session=False)


def seed_demo_database(db: Session, email: str, password: str) -> dict:
    if not email or not password:
        raise ValueError("demo user email and password are required")
    user = db.query(User).filter(User.email == email).first()
    if not user:
        user = User(email=email, password_hash=get_password_hash(password))
        db.add(user)
        db.flush()
    else:
        user.password_hash = get_password_hash(password)
    _clear_demo_rows(db, user)

    today = date.today()
    stocks = {}
    for symbol, name, sector, base in STOCKS:
        stock = db.query(Stock).filter(Stock.symbol == symbol).first()
        if not stock:
            stock = Stock(symbol=symbol, name=name, market="SZ", sector=sector)
            db.add(stock)
            db.flush()
        stocks[symbol] = stock
        previous = base * 0.94
        for offset in range(140, 0, -1):
            d = today - timedelta(days=offset)
            trend = base * (1 + 0.0007 * (140 - offset))
            close = trend * (1 + 0.025 * math.sin(offset / 8))
            open_price = close * 0.997
            high, low = close * 1.012, close * 0.985
            db.add(MarketData(stock_id=stock.id, date=d, open=open_price, high=high, low=low, close=close, volume=8_000_000 + offset * 21000))
            if offset % 7 == 0:
                db.add(StockKline(stock_id=stock.id, period="weekly", trade_date=d, open=open_price, high=high, low=low, close=close, volume=1_000_000, amount=close * 1_000_000, pct_change=(close / previous - 1) * 100))
            previous = close
        latest = close
        db.add(StockQuote(stock_id=stock.id, quote_time=datetime.utcnow(), latest_price=latest, change_pct=1.28, change_amount=latest * .0128, volume=9_200_000, amount=latest * 9_200_000, pe_dynamic=14.8, pb=1.45, raw={"source": DEMO_SOURCE}))
        db.add(CompanyFundamental(stock_id=stock.id, snapshot_date=today, industry=sector, listed_date=date(2010, 1, 1), staff_num=50000, main_business=f"{name}核心业务与智能制造", business_scope="研发、制造与销售", company_intro=f"{name}演示基本面资料", management_info={"source": DEMO_SOURCE}, raw={"source": DEMO_SOURCE}))
        for year in range(2022, 2025):
            db.add(CompanyFinancial(stock_id=stock.id, report_date=date(year, 12, 31), report_name=f"{year}年年度报告", report_type="annual", eps=1.2 + year % 3 * .2, revenue=100e8 + year * 2e8, net_profit=12e8 + year * 3e7, gross_margin=28.5, roe=11.2, asset_liability_ratio=48.0, operating_cashflow=15e8, yoy_revenue=8.6, yoy_net_profit=10.1, source=DEMO_SOURCE, dataset=DEMO_SOURCE, raw={"source": DEMO_SOURCE}))
        for i in range(4):
            db.add(Document(stock_id=stock.id, stock_symbol=symbol, doc_type="news", title=f"{name}经营动态 {i + 1}", content=f"{name}近期经营保持稳定，研发投入和现金流表现良好。该内容为本地演示数据。", source=DEMO_SOURCE, published_at=datetime.utcnow() - timedelta(days=i + 1), doc_metadata={"demo": True}))

    db.add(Document(doc_type="macro", title="政策与市场环境", content="流动性环境保持平稳，演示页面可在无外部数据源时正常浏览。", source=DEMO_SOURCE, published_at=datetime.utcnow(), doc_metadata={"demo": True}))
    profile = UserProfile(user_id=user.id, risk_level="medium", investment_horizon="long", income=240000, assets=800000, disposable_funds=300000, experience_years=3, max_drawdown=.2, risk_budget=.03, target_return=.12, max_single_position=.2, style="balanced", persona="balanced_growth", questionnaire_answers={"q1": "balanced", "q2": "long"}, preferences={"demo": True})
    db.add(profile)
    positions = []
    for symbol, quantity in (("000333", 500), ("002415", 800)):
        stock = stocks[symbol]
        pos = Position(user_id=user.id, stock_id=stock.id, quantity=quantity, avg_price=stock.quotes[-1].latest_price if stock.quotes else 30, status="open")
        db.add(pos); db.flush(); positions.append(pos)
        db.add(UserStockHolding(user_id=user.id, stock_id=stock.id, stock_symbol=symbol, quantity=quantity, avg_price=pos.avg_price, total_buy_amount=quantity * pos.avg_price))
        db.add(PortfolioTrade(user_id=user.id, stock_id=stock.id, side="buy", quantity=quantity, price=pos.avg_price, trade_time=datetime.utcnow() - timedelta(days=30), note="演示建仓"))

    snapshot = RankingSnapshot(snapshot_date=today, snapshot_type=DEMO_SOURCE, status="completed", summary={"source": DEMO_SOURCE, "count": len(stocks)})
    db.add(snapshot); db.flush()
    for rank, (symbol, stock) in enumerate(stocks.items(), 1):
        score = 92 - rank * 4
        db.add(RankingItem(snapshot_id=snapshot.id, stock_id=stock.id, stock_symbol=symbol, rank=rank, total_score=score, news_score=score, stock_score=score-1, macro_score=78, financial_score=score+1, fundamental_score=score, data_drive_score=score, emotion_drive_score=75, conflict_signal=False, recommendation_action="hold" if rank > 2 else "buy", recommendation_confidence=.78, recommendation_summary="演示规则评分", expert_payload={"source": DEMO_SOURCE}, investment_payload={"source": DEMO_SOURCE}))

    analysis_stock = stocks["000333"]
    analysis = Analysis(user_id=user.id, stock_id=analysis_stock.id, final_action="hold", position_size=.12, rationale={"summary": "基本面稳健，建议观察估值与趋势", "source": DEMO_SOURCE}, risk_notes=["演示数据不构成投资建议"])
    db.add(analysis); db.flush()
    for expert in ("基本面", "技术面", "风险控制"):
        db.add(ExpertSignal(analysis_id=analysis.id, expert_name=expert, signal="hold", score=.72, confidence=.78, fallback=True, horizon="medium", key_factors=["演示规则"], risk_flags=["无实时行情"], evidence=["本地数据库"]))
    plan = TradePlan(user_id=user.id, stock_id=analysis_stock.id, position_id=positions[0].id, side="hold", entry_low=65, entry_high=69, ladder_prices=[65, 67, 69], stop_loss_price=61, take_profit_price=76, suggested_shares=0, hold_days="1-3个月", status="active", rationale={"source": DEMO_SOURCE})
    db.add(plan); db.flush()
    db.add(TradeSignal(user_id=user.id, stock_id=analysis_stock.id, trade_plan_id=plan.id, side="hold", signal_type="watch", trigger_price=68, suggested_shares=0, confidence=.76, reason="演示规则：等待趋势确认"))
    db.commit()
    return {"email": email, "stocks": len(stocks), "market_days": 140, "source": DEMO_SOURCE}
