export const demoRankingSnapshot = {
  id: 1001,
  snapshot_date: '2026-08-15',
  snapshot_type: 'post_close',
  status: 'completed',
  summary: {
    top_n: 5,
    source: 'development_fixture',
    note: '仅用于前端开发预览，字段与后端 RankingSnapshotOut 保持一致',
  },
  generated_at: '2026-08-15T16:12:00+08:00',
  items: [
    {
      id: 1,
      stock_symbol: '000001',
      rank: 1,
      total_score: 82.6,
      news_score: 78.0,
      stock_score: 86.0,
      macro_score: 75.0,
      financial_score: 88.0,
      fundamental_score: 86.0,
      data_drive_score: 85.4,
      emotion_drive_score: 77.2,
      conflict_signal: false,
      recommendation_action: 'buy',
      recommendation_confidence: 0.84,
      recommendation_summary: '五项专家信号整体一致，数据与基本面评分领先。',
      expert_payload: {},
      investment_payload: {},
    },
    {
      id: 2,
      stock_symbol: '600036',
      rank: 2,
      total_score: 79.8,
      news_score: 74.0,
      stock_score: 81.0,
      macro_score: 76.0,
      financial_score: 85.0,
      fundamental_score: 83.0,
      data_drive_score: 81.5,
      emotion_drive_score: 74.8,
      conflict_signal: false,
      recommendation_action: 'buy',
      recommendation_confidence: 0.79,
      recommendation_summary: '财务与基本面信号稳定，短期情绪强度一般。',
      expert_payload: {},
      investment_payload: {},
    },
    {
      id: 3,
      stock_symbol: '000333',
      rank: 3,
      total_score: 76.4,
      news_score: 72.0,
      stock_score: 79.0,
      macro_score: 73.0,
      financial_score: 82.0,
      fundamental_score: 78.0,
      data_drive_score: 79.6,
      emotion_drive_score: 70.1,
      conflict_signal: true,
      recommendation_action: 'hold',
      recommendation_confidence: 0.68,
      recommendation_summary: '量价与情绪信号存在分歧，建议继续观察。',
      expert_payload: {},
      investment_payload: {},
    },
    {
      id: 4,
      stock_symbol: '601318',
      rank: 4,
      total_score: 73.9,
      news_score: 70.0,
      stock_score: 74.0,
      macro_score: 72.0,
      financial_score: 79.0,
      fundamental_score: 76.0,
      data_drive_score: 74.8,
      emotion_drive_score: 69.4,
      conflict_signal: false,
      recommendation_action: 'hold',
      recommendation_confidence: 0.65,
      recommendation_summary: '中期基本面评价稳定，当前缺少明确催化信号。',
      expert_payload: {},
      investment_payload: {},
    },
    {
      id: 5,
      stock_symbol: '600519',
      rank: 5,
      total_score: 71.7,
      news_score: 68.0,
      stock_score: 70.0,
      macro_score: 69.0,
      financial_score: 80.0,
      fundamental_score: 77.0,
      data_drive_score: 71.0,
      emotion_drive_score: 66.5,
      conflict_signal: true,
      recommendation_action: 'hold',
      recommendation_confidence: 0.61,
      recommendation_summary: '基本面保持高分，但数据与情绪信号偏弱。',
      expert_payload: {},
      investment_payload: {},
    },
  ],
}

export const demoProfile = {
  id: 1,
  user_id: 1,
  risk_level: 'medium',
  investment_horizon: 'long',
  income: 180000,
  assets: 600000,
  disposable_funds: 120000,
  experience_years: 3,
  max_drawdown: 0.2,
  risk_budget: 0.02,
  target_return: 0.12,
  max_single_position: 0.15,
  style: 'balanced',
  persona: 'balanced_growth',
  questionnaire_answers: {
    disposable_funds: 120000,
    loss_aversion: 2,
    risk_comfort: 2,
    time_horizon: 3,
    financial_literacy: 2,
    scoring: {
      risk_sensitivity_index: 0.56,
      funds_bucket: '100k-300k',
      suggested_order_budget: 18000,
      risk_budget: 0.02,
      max_single_position: 0.15,
    },
  },
  preferences: {},
}

export const demoQuestionnaire = {
  required_order: ['disposable_funds', 'loss_aversion', 'risk_comfort', 'time_horizon', 'financial_literacy'],
  questions: {
    disposable_funds: { title: '可支配资金（人民币）', type: 'number', min: 0 },
    loss_aversion: { title: '亏损厌恶', options: { 1: '高', 2: '较高', 3: '中等', 4: '较低' } },
    risk_comfort: { title: '风险承受偏好', options: { 1: '保守', 2: '稳健', 3: '进取', 4: '激进' } },
    time_horizon: { title: '投资期限', options: { 1: '1 年以内', 2: '1-3 年', 3: '3-5 年', 4: '5 年以上' } },
    financial_literacy: { title: '金融知识水平', options: { 1: '入门', 2: '基础', 3: '熟练', 4: '专业' } },
  },
}

export const demoPositions = [
  { id: 1, stock_symbol: '000001', quantity: 1200, avg_price: 11.86, status: 'open', updated_at: '2026-08-15T15:08:00+08:00' },
  { id: 2, stock_symbol: '600036', quantity: 500, avg_price: 39.42, status: 'open', updated_at: '2026-08-15T15:08:00+08:00' },
]

export const demoTrades = [
  { id: 1, stock_symbol: '000001', side: 'buy', quantity: 1200, price: 11.86, trade_time: '2026-08-12T10:18:00+08:00', note: '分批建仓' },
  { id: 2, stock_symbol: '600036', side: 'buy', quantity: 500, price: 39.42, trade_time: '2026-08-13T14:26:00+08:00', note: '初始仓位' },
]

export const demoTradePlans = [
  { id: 1, stock_symbol: '000001', side: 'buy', suggested_shares: 400, stop_loss_price: 10.92, take_profit_price: 13.68, hold_days: '20-40' },
]

export const demoTradeSignals = [
  { id: 1, stock_symbol: '000001', side: 'buy', signal_type: 'watch', confidence: 0.78, created_at: '2026-08-15T16:20:00+08:00' },
]
